### ISSUE TITLE
Update shorthand with increment?

### ISSUE THREAD

**Issue by dysfunct** [voku/simple-mysqli#33]
Hey there - just wondering if there's anyway to get the equivalent of `UPDATE (foo) SET foo = foo + 1` using the `$db->update(string $table, array $update)` syntax. I've tried a few different ways but none have worked and I don't see it covered in the docs.

Cheers and thank you!

**Comment by voku** [comment]
Example: UPDATE with "foo = foo + 1"

```php
  $where = [
      'id =' => '123'
  ];
  $data = [
      'foo' => ['foo +' => 1],
      'bar' => 'lall',
  ];
  $resultSelect = $db->update('page', $data, $where);
```
