### ISSUE TITLE
Use in another namespace/class

### ISSUE THREAD

**Issue by Organizer21** [voku/simple-mysqli#43]
I hope I can ask a stupid Q as I'm still learning things with classes and namespaces in general. If I want to use your wrappers DB connection in another custom namespaces class function i have, what would be the best/correct approach to get the connection object for a custom query?

**Comment by voku** [comment]
You can use the "use" statement see example in the README or even better in the tests.

Namespaces are pretty simple, it's only something like a prefix for the classes and if you are using a good IDE (e.g. PhpStorm https://www.jetbrains.com/phpstorm/eap/) then you don't need to think much about this stuff.
