### ISSUE TITLE
Select IN causing issues.

### ISSUE THREAD

**Issue by michaelmarkie** [voku/simple-mysqli#46]
#### What is this feature about (expected vs actual behaviour)?
Replacing "IN" in "**in**strument_id".

#### How can I reproduce it?
```php
$select = $db->select('instruments', ['instrument_id IN' => [13]]);
```
The above will generate the below
```sql
SELECT * FROM `instruments` WHERE ( `strument_id` IN (13))
```

What I expected was:
```sql
SELECT * FROM `instruments` WHERE ( `instrument_id` IN (13))
```
#### Any additional information?
Issue begins on DB.php line 458, I think it needs to find the last occurence of IN as opposed to replacing the first.

**Comment by voku** [comment]
Thanks for the good bug report, fixed in version 8.2.5

You were right :+1:  and now we use ```UTF8::str_replace_last()"``` instead of ```str_replace()```.
