### ISSUE TITLE
Is there a way to execute an SQL file/multiple queries at once ?

### ISSUE THREAD

**Issue by redasakhi** [voku/simple-mysqli#47]
#### What is this feature about (expected vs actual behaviour)?
Execute multiple updates/inserts queries inline or from a file (file_get_contents)

#### How can I reproduce it?
$db->query("INSERT INTO ......; INSERT INTO .....;");

#### Does it take minutes, hours or days to fix?
I think minutes. Just make ->query(..) execute as a block or add a function ->queries(...)

#### Any additional information?

**Comment by voku** [comment]
Please try to use multi_query: https://github.com/voku/simple-mysqli/blob/master/tests/SimpleDbTest.php#L1598

**Comment by redasakhi** [comment]
It worked like a charm.
I haven't paid attention to those test functions. There must be a reference to this in the ReadMe file.
Thanks.

**Comment by voku** [comment]
Yep, you are right. I need to update some README files of my open source projects. :)

**Comment by voku** [comment]
README updated: https://github.com/voku/simple-mysqli/commit/d18470a5360ce572f281dcf41ea0e5cbbcfb54a3
