### ISSUE TITLE
Fatal error in Helper when using PHP PHP 8.0.8 

### ISSUE THREAD

**Issue by maranemil** [voku/simple-mysqli#50]
#### What is this feature about (expected vs actual behaviour)?
\mysqli_get_server_version($mysqli_link) is causing Fatal error because mysqli_get_server_version() expects 0 arguments

#### How can I reproduce it?
just run it with PHP 8.X 

#### Does it take minutes, hours or days to fix?
minutes
instead of \mysqli_get_server_version($mysqli_link) 
should be only \mysqli_get_server_version()

#### Any additional information?

Fatal error: Uncaught ArgumentCountError: mysqli_get_client_version() expects exactly 0 arguments, 1 given in /vendor/voku/simple-mysqli/src/voku/db/Helper.php

**Comment by voku** [comment]
Thanks for the bug report: fixed in version 8.2.10
