### ISSUE TITLE
Expose a way to sanitize strings

### ISSUE THREAD

**Issue by willisplummer** [voku/simple-mysqli#55]
I'm trying to port over some old PHP 5.6 code that was making use of sanitization -- when it's just for use in a query, it's been easy to convert to the new query syntax and use parameters, but there are a few instances where the old code was sanitizing and then writing the result to a file -- I just am trying to faithfully update the code and was wondering if there's a way to get access to sanitization through this API?

**Comment by voku** [comment]
You can call `escape` from the DB class. But this is more escaping + encoding fixing than sanitization.

**Comment by willisplummer** [comment]
Thanks!
